model_params:
  model_seed: 1234
  name: 'AssortmentNN'
  Nprod_Veclen: 20

  Num_CrossEffectLayer: 1
  Cross_midLayers: [20]

  
  
data_params:
  data_seed: 1234

  data_path: ""

  Assortments: "ASSORT.npy"
  Final_choices: "SAMP.npy"
  Real_prob: "PROB.npy"


  train_amount: 0

  valid_amount: 0
  
  test_amount: 0

  device: "gpu"


exp_params:
  exp_seed: 1234

  train_batch_size: 100
  valid_batch_size: 100
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.99

  device: "gpu"
  max_epochs: 100

logging_params:

  log_name: "EXP1_AssortmentNN"

  log_save_perEpoch: 5

  log_save_stack: 4

